src/Entity/Episode.php
<?php

namespace App\Entity;

use DateTime;
use Exception;
use SimplePie_Item;

/**
 * Podcast episode
 */
class Episode
{
    /**
     * Bitrate in kbit/s
     */
    const BITRATE_KBPS = 192;

    /**
     * @var SimplePie_Item
     */
    private $item;

    /**
     * @var RssConfig
     */
    private $rssConfig;

    /**
     * Episode constructor.
     *
     * @param SimplePie_Item $item
     * @param RssConfig $rssConfig
     */
    public function __construct(SimplePie_Item $item, RssConfig $rssConfig)
    {
        $this->item = $item;
        $this->rssConfig = $rssConfig;
    }

    /**
     * @return string
     */
    public function getTitle(): string
    {
        return html_entity_decode($this->item->get_title());
    }


    /**
     * @return string
     */
    public function getLink(): string
    {
        return $this->item->get_link();
    }

    /**
     * @return string
     */
    public function getDescription(): string
    {
        return $this->item->get_description();
    }

    /**
     * @return string
     */
    public function getContent(): string
    {
        return $this->item->get_content();
    }

    /**
     * @return string
     */
    public function getUrl(): string
    {
        return $this->item->get_enclosure()->link;
    }

    /**
     * @return string
     */
    public function getLength(): string
    {
        return $this->item->get_enclosure()->length;
    }

    /**
     * @return int
     */
    public function getDuration(): int
    {
        $bitrateKbps = ($this->rssConfig->getBitrateKbps()) ?: self::BITRATE_KBPS;

        if ($this->item->get_enclosure()->duration) {
            $duration = $this->item->get_enclosure()->duration / 60;
        } else {
            $duration = $this->calculateMp3Duration(
                $bitrateKbps,
                $this->item->get_enclosure()->length
            );
        }
        return $duration;
    }

    /**
     * @return DateTime
     * @throws Exception
     */
    public function getPubDate()
    {
        return new DateTime(date("Y-m-d", strtotime($this->item->get_date())));
    }

    /**
     * @return mixed
     */
    public function getNumber()
    {
        return $this->item->get_item_tags(SIMPLEPIE_NAMESPACE_ITUNES, 'episode')[0]['data'];
    }

    /**
     * @return mixed
     */
    public function getSeason()
    {
        return $this->item->get_item_tags(SIMPLEPIE_NAMESPACE_ITUNES, 'season')[0]['data'];
    }

    /**
     * @return float
     */
    public function getFilesize(): float
    {
        return $this->item->get_enclosure()->length * 0.000001;
    }

    /**
     * Calculates approximate duration of mp3 file
     *
     * @param $bitrate
     * @param $length
     * @return false|float
     */
    private function calculateMp3Duration($bitrate, $length)
    {
        $seconds = ((int)$length * 0.008)/$bitrate;

        return floor($seconds/60);
    }
}

src/Entity/Feed.php
<?php

namespace App\Entity;


use SimplePie;

class Feed
{
    /**
     * @var SimplePie
     */
    private $feed;

    /**
     * Feed constructor.
     *
     * @param SimplePie $feed
     */
    public function __construct(SimplePie $feed)
    {
        $this->feed = $feed;
    }

    /**
     * @return string|null
     */
    public function getTitle()
    {
        return $this->feed->get_title();
    }

    /**
     * @return string|null
     */
    public function getDescription()
    {
        return html_entity_decode($this->feed->get_description());
    }

    /**
     * @return string|null
     */
    public function getImage()
    {
        return $this->feed->get_image_url();
    }

    /**
     * @return string|null
     */
    public function getLanguage()
    {
        return $this->feed->get_language();
    }
}

src/Entity/Item.php
<?php

namespace App\Entity;

use DateTime;
use Exception;
use SimplePie_Item;

/**
 * Generic item
 */
class Item
{
    /**
     * @var SimplePie_Item
     */
    private $item;

    /**
     * @var RssConfig
     */
    private $rssConfig;

    /**
     * Item constructor.
     *
     * @param SimplePie_Item $item
     * @param RssConfig $rssConfig
     */
    public function __construct(SimplePie_Item $item, RssConfig $rssConfig)
    {
        $this->item = $item;
        $this->rssConfig = $rssConfig;
    }

    /**
     * @return string
     */
    public function getTitle(): string
    {
        return html_entity_decode($this->item->get_title());
    }


    /**
     * @return string
     */
    public function getLink(): string
    {
        return $this->item->get_link();
    }

    /**
     * @return string
     */
    public function getDescription(): string
    {
        if (
            $this->item->get_content() &&
            $this->rssConfig->isUseContent()
        ) {
            $description = $this->item->get_content();
        } else {
            $description = $this->item->get_description();
        }

        return $description;
    }

    /**
     * @return string
     */
    public function getUrl(): string
    {
        return $this->item->get_enclosure()->link;
    }

    /**
     * @return DateTime
     * @throws Exception
     */
    public function getPubDate()
    {
        return new DateTime(date("Y-m-d", strtotime($this->item->get_date())));
    }
}

src/Controller/RssFeedController.php
<?php

namespace App\Controller;

use App\Entity\Episode;
use App\Entity\Feed;
use App\Entity\PageConfig;
use App\Entity\Item;
use App\Entity\RssConfig;
use App\Service\RssConfigurator;
use Exception;
use Psr\Log\LoggerInterface;
use SimplePie;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\KernelInterface;

/**
 * Class RssFeedController
 *
 * @package App\Controller
 */
class RssFeedController extends AbstractController
{
    /**
     * Limit of feed items
     */
    const ITEM_LIMIT = 10;

    /**
     * Generate podcast site
     */
    const PODCAST = 1;

    /**
     * Generate blog site
     */
    const BLOG = 2;

    /**
     * @var array
     */
    private $episodes = [];

    /**
     * @var array
     */
    private $items = [];

    /**
     * @var RssConfig
     */
    private $rssConfig;

    /**
     * @var RssConfigurator
     */
    private $rssConfigurator;

    /**
     * @var LoggerInterface
     */
    private $logger;

    /**
     * @var string
     */
    private $projectDir;

    /**
     * RssFeedController constructor.
     *
     * @param RssConfigurator $rssConfigurator
     * @param KernelInterface $kernel
     * @param LoggerInterface $logger
     */
    public function __construct(
        RssConfigurator $rssConfigurator,
        KernelInterface $kernel,
        LoggerInterface $logger
    )
    {
        $this->rssConfigurator = $rssConfigurator;
        $this->rssConfig = $this->rssConfigurator->getRssConfiguration();
        $this->projectDir = $kernel->getProjectDir();
        $this->logger = $logger;
    }

    /**
     * Renders Feed site
     *
     * @param Request $request
     * @param $feedUrl
     * @return Response
     * @throws Exception
     */
    public function generateFeedSite(Request $request, $feedUrl = '')
    {
        $rssFeedUrl = ($this->rssConfig->getRssFeedUrl()) ?: $feedUrl;

        // Get required theme
        $theme = ($this->rssConfig->isChildTheme()) ? 'rss_feed_child/' : 'rss_feed/';

        if (!($feed = $this->fetchFeed($rssFeedUrl))) {
            return $this->render($theme . 'error.html.twig', [
                'rssConfig' => $this->rssConfig
            ]);
        }

        // Get page and item configuration
        $limit = ($this->rssConfig->getItemLimit()) ?: self::ITEM_LIMIT;
        $pageConfig = PageConfig::createFromRequest($request, $limit, $feed);

        // Get items and template names
        if ($this->rssConfig->isPodcastType()) {
            $this->episodes = $this->getEpisodes($feed, $pageConfig);
            $feedTemplate = 'podcast.html.twig';
            $itemTemplate = '_episodes.html.twig';
        } else {
            $this->items = $this->getItems($feed, $pageConfig);
            $feedTemplate = 'generic.html.twig';
            $itemTemplate = '_items.html.twig';
        }

        // Check if HTMX request
        if (!$request->server->has('HTTP_HX_REQUEST')) {
            $template = $theme . $feedTemplate;
        } else {
            $template = $theme . $itemTemplate;
        }

        // Render appropriate template
        $result = $this->render(
            $template,
            $this->getTemplateVariables(
                new Feed($feed),
                $pageConfig
            )
        );

        if (!$result) {
            $result = $this->render($theme . 'error.html.twig', [
                'rssConfig' => $this->rssConfig
            ]);
        }
        return $result;
    }

    /**
     * Fetches RSS feed as SimplePie object
     *
     * @param $feedUrl
     * @return SimplePie|null
     */
    private function fetchFeed($feedUrl): ?SimplePie
    {
        $feed = new SimplePie();
        $feed->set_feed_url($feedUrl);
        $feed->enable_order_by_date(false);
        if (!is_dir($this->projectDir . '/var/cache/rss')) {
            mkdir($this->projectDir . '/var/cache/rss');
        }
        $feed->set_cache_location($this->projectDir . '/var/cache/rss');

        $feed->init();

        if ($feed->error) {
            $this->logger->error(
                $feed->error()
            );
            return null;
        } else {
            return $feed;
        }
    }

    /**
     * Returns podcast episodes
     *
     * @param SimplePie $feed
     * @param PageConfig $pageConfig
     * @return array
     * @throws Exception
     */
    private function getEpisodes(SimplePie $feed, PageConfig $pageConfig): array
    {
        for ($i = $pageConfig->getStartItem(); $i < $pageConfig->getMaxItems(); $i++) {

            $item = $feed->get_item($i);

            $episode = new Episode($item, $this->rssConfig);

            $this->episodes[] = $episode;
        }
        return $this->episodes;
    }

    /**
     * Returns generic items
     *
     * @param SimplePie $feed
     * @param PageConfig $pageConfig
     * @return array
     */
    private function getItems(SimplePie $feed, PageConfig $pageConfig): array
    {
        for ($i = $pageConfig->getStartItem(); $i < $pageConfig->getMaxItems(); $i++) {

            $feedItem = $feed->get_item($i);

            $item = new Item($feedItem, $this->rssConfig);

            $this->items[] = $item;
        }
        return $this->items;
    }

    /**
     * Returns an array of template variables
     *
     * @param Feed $feed
     * @param PageConfig $pageConfig
     * @return array
     */
    private function getTemplateVariables(
        Feed $feed,
        PageConfig $pageConfig
    ): array
    {
        if ($this->rssConfig->isPodcastType()) {
            $name = 'episodes';
            $items = $this->episodes;
        } else {
            $name = 'items';
            $items = $this->items;
        }
        return [
            'feed' => $feed,
            $name => $items,
            'pageConfig' => $pageConfig,
            'rssConfig' => $this->rssConfig,
        ];
    }
}

templates/rss_feed/_episodes.html.twig
{% block episodes %}

        {% if rssConfig.dateFormat %}
            {% set dateFormat = rssConfig.dateFormat %}
        {% else %}
            {% set dateFormat = 'Y-m-d' %}
        {% endif %}

        {% if episodes %}
            {% for episode in episodes %}
                <div class="row episode">
                    <div class="twelve column episode-date">
                        <span>{{ episode.pubDate|date(dateFormat) }}</span>
                    </div>
                    <div class="row">
                        <div class="one-half column episode-title">
                            <h2>{{ episode.title }}</h2> <br>
                        </div>
                        <div class="one-half column">
                            <p>{{ episode.content|striptags('<a>')|raw }}</p>
                            <div class="episode-audio fade-in">
                                <audio controls
                                       preload="none">
                                    <source src="{{ episode.url }}"
                                            type="audio/mpeg">
                                </audio>
                            </div>
                            <p>Podcast: <a href="{{ episode.url }}" download>Download</a> ({{ episode.duration }} min
                                | {{ episode.filesize|round(1, 'floor') }} MB)</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
            {% block loader %}{% endblock %}
        {% else %}
            {{ rssConfig.noResults }}
        {% endif %}
{% endblock %}

{% block pagination %}
    {{ include('rss_feed/loader/_pagination.html.twig', {pageConfig: pageConfig}) }}
{% endblock %}

templates/rss_feed/_footer.html.twig
<footer>
    © {{ "now"|date("Y") }} {{ rssConfig.copyright}} {% if rssConfig.imprintUrl %}| <a target="_blank" href="{{ rssConfig.imprintUrl }}">{{ rssConfig.imprintLinkName }}</a>{% endif %}
</footer>

templates/rss_feed/_hero.html.twig
{% block hero %}
    {% if rssConfig.title is defined and rssConfig.title %}
        {% set title = rssConfig.title %}
    {% else %}
        {% set title = feed.title %}
    {% endif %}
    {% if rssConfig.description is defined and rssConfig.description %}
        {% set description = rssConfig.description %}
    {% else %}
        {% set description = feed.description %}
    {% endif %}
    {% if rssConfig.backgroundColor is defined and rssConfig.backgroundColor %}
        {% set backgroundColor = 'style=background-color:' ~ rssConfig.backgroundColor ~ ';' %}
    {% else %}
        {% set backgroundColor = '' %}
    {% endif %}
    {% if rssConfig.fontColor is defined and rssConfig.fontColor %}
        {% set fontColor = 'style=color:' ~ rssConfig.fontColor ~ ';' %}
    {% else %}
        {% set fontColor = '' %}
    {% endif %}
    {% if logo %}
        {% set image = asset('image/' ~ logo) %}
    {% else %}
        {% set image = feed.image %}
    {% endif %}
    <div class="hero-bg" {{ backgroundColor ?: '' }}>
        <div class="hero-text" {{ fontColor ?: '' }}>
            {% if image %}
                <div class="fade-in">
                    <img alt="{{ title }}" src="{{ image }}">
                </div>
            {% endif %}
            <div class="feed-title-description">
                {% if title %}
                <h1>{{ title }}</h1>
                {% endif %}
                {% if description %}
                <p>{{ description }}</p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/rss_feed/_items.html.twig
{% block items %}
    <div class="container">
        {% if rssConfig.dateFormat %}
            {% set dateFormat = rssConfig.dateFormat %}
        {% else %}
            {% set dateFormat = 'Y-m-d' %}
        {% endif %}

        {% if items %}
            {% for row in items|batch(3) %}
                <div class="row">
                    {% for item in row %}
                        <div class="one-third column">
                            <div class="item-date">
                                <span>{{ item.pubDate|date(dateFormat) }}</span>
                            </div>
                            <div class="item-title">
                                <a href="{{ item.link }}">
                                    <h2>{{ item.title }}</h2>
                                </a>
                                <p class="item-description">
                                    {{ item.description|striptags('<a>')|raw }}
                                </p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% endfor %}
        {% else %}
            {{ rssConfig.noResults }}
        {% endif %}
    </div>
{% endblock %}

{% block pagination %}
    {{ include('rss_feed/loader/_pagination.html.twig', {pageConfig: pageConfig}) }}
{% endblock %}

templates/rss_feed/_metatags.html.twig
<meta name="description" content="{{ feed.description }}">
<meta name="author" content="{{ feed.title }}">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta property="og:url" content="{{ pageConfig.url }}">
<meta property="og:type" content="website">
<meta property="og:title" content="{{ feed.title }}">
<meta property="og:description" content="{{ feed.description }}">
<meta property="og:image" content="{{ feed.image }}">
{# Canonical Link #}
{% if rssConfig.canonicalLink %}
<link rel="canonical" href="{{ rssConfig.canonicalLink }}">
{% endif %}

templates/rss_feed/error.html.twig
{% extends 'rss_feed/feed_site.html.twig' %}

{% set feed = {
    'title': '',
    'description': '',
    'image': asset('image/error.jpg')} %}

{% block title %}Ooops, an error occurred...{% endblock %}

    {% block hero %}
        {{ include('rss_feed/_hero.html.twig', {feed: feed, logo: rssConfig.logo}) }}
    {% endblock %}

{% block feed_contents %}
    <div class="row">
        <div class="twelve column">
            <h1>Nothing to see!</h1>
        </div>
        <div class="row">
            <div class="twelve column">
                <h2>
                    {% if rssConfig.feedError %}
                        {{ rssConfig.feedError }}
                    {% else %}
                        Just return to the <a href="{{ path('episodes') }}">homepage</a>.
                    {% endif %}
                </h2>
            </div>
        </div>
    </div>
{% endblock %}

templates/rss_feed/feed_site.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% block hero %}{% endblock %}
    <div class="margin-top">
        {% block feed_contents %}{% endblock %}
        {% block pagination %}{% endblock %}
    </div>
    {% block footer %}{% endblock %}
{% endblock %}

templates/rss_feed/generic.html.twig
{% extends 'rss_feed/feed_site.html.twig' %}

{% block language %}{{ feed.language }}{% endblock %}
{% block title %}{{ feed.title }} - {{ feed.description }}{% endblock %}
{% block metatags %}
    {{ include('rss_feed/_metatags.html.twig', {feed: feed, pageConfig: pageConfig, rssConfig: rssConfig}) }}
{% endblock %}

{% block favicon %}
    {% if rssConfig.favicon %}
        {% set favicon = 'image/' ~ rssConfig.favicon %}
    {% else %}
        {% set favicon = 'image/favicon_default.ico' %}
    {% endif %}
    <link rel="icon" href="{{ asset(favicon) }}" title="Favicon">
{% endblock %}

{% block hero %}
    {{ include('rss_feed/_hero.html.twig', {feed: feed, logo: rssConfig.logo}) }}
{% endblock %}

{% block feed_contents %}
<div class="container" id="feed-content">
    {% block items %}
        {{ include('rss_feed/_items.html.twig', {feed: feed, logo: rssConfig.logo}) }}
    {% endblock %}
</div>
{% endblock %}

{% block pagination %}{% endblock %}
{% block footer %}
    {{ include('rss_feed/_footer.html.twig', {rssConfig: rssConfig}) }}
{% endblock %}

templates/rss_feed/podcast.html.twig
{% extends 'rss_feed/feed_site.html.twig' %}

{% block language %}{{ feed.language }}{% endblock %}
{% block title %}{{ feed.title }} - {{ feed.description }}{% endblock %}
{% block metatags %}
    {{ include('rss_feed/_metatags.html.twig', {feed: feed, pageConfig: pageConfig, rssConfig: rssConfig}) }}
{% endblock %}

{% block favicon %}
    {% if rssConfig.favicon %}
        {% set favicon = 'image/' ~ rssConfig.favicon %}
    {% else %}
        {% set favicon = 'image/favicon_default.ico' %}
    {% endif %}
    <link rel="icon" href="{{ asset(favicon) }}" title="Favicon">
{% endblock %}

{% block hero %}
    {{ include('rss_feed/_hero.html.twig', {feed: feed, logo: rssConfig.logo}) }}
{% endblock %}

{% block feed_contents %}
<div class="container" id="feed-content">
    {% block episodes %}
        {{ include('rss_feed/_episodes.html.twig', {feed: feed, logo: rssConfig.logo}) }}
    {% endblock %}
</div>
    <script>
        htmx.onLoad(function() {
            rssPlayer();
        });
    </script>
{% endblock %}

{% block pagination %}{% endblock %}
{% block footer %}
    {{ include('rss_feed/_footer.html.twig', {rssConfig: rssConfig}) }}
{% endblock %}